import Layout from '../../components/Layout'
import { AffiliateDisclosure } from '../../components/AffiliateLink'
import NewsletterSignup from '../../components/NewsletterSignup'
import Breadcrumbs from '../../components/Breadcrumbs'
import Link from 'next/link'
import { getAllReviews, getReviewBySlug, getReadingTime } from '../../lib/reviews'

const SITE_URL = 'https://pilottools.ai'

export default function ReviewPage({ review, relatedReviews }) {
  if (!review) return null

  const canonicalUrl = `${SITE_URL}/reviews/${review.slug}/`
  const structuredData = [
    {
      "@context": "https://schema.org",
      "@type": "Review",
      "headline": review.title,
      "description": review.excerpt,
      "author": {
        "@type": "Organization",
        "name": review.author,
      },
      "datePublished": review.published_date,
      "reviewRating": {
        "@type": "Rating",
        "ratingValue": review.rating,
        "bestRating": 5,
      },
      "itemReviewed": {
        "@type": "SoftwareApplication",
        "name": review.tool_name,
        "url": review.tool_website,
        "applicationCategory": "BusinessApplication",
      },
      "mainEntityOfPage": canonicalUrl,
    }
  ]

  // Review HTML is generated by our build-time content pipeline (not user input)
  const contentHtml = review.html || ''
  const midPoint = Math.floor(contentHtml.length / 2)
  const splitIndex = contentHtml.indexOf('</p>', midPoint)
  const hasEnoughContent = contentHtml.length > 1000 && splitIndex !== -1
  const firstHalf = hasEnoughContent ? contentHtml.substring(0, splitIndex + 4) : contentHtml
  const secondHalf = hasEnoughContent ? contentHtml.substring(splitIndex + 4) : ''

  return (
    <Layout
      title={review.title}
      description={review.excerpt}
      canonical={canonicalUrl}
      ogType="article"
      structuredData={structuredData}
    >
      <Breadcrumbs items={[
        { label: 'Home', href: '/' },
        { label: 'Reviews', href: '/reviews/' },
        { label: review.tool_name }
      ]} />

      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <header className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="badge-blue">{review.category}</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-dt mb-4 leading-tight">{review.title}</h1>

          <div className="mb-6 p-6 bg-dark-surface rounded-lg border border-dark-border">
            <div className="flex items-center gap-4 mb-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-2xl font-bold text-accent">
                    {'★'.repeat(Math.floor(review.rating))}
                    {review.rating % 1 !== 0 && '½'}
                  </span>
                  <span className="text-xl text-dt-muted">{review.rating}/5</span>
                </div>
                <p className="text-sm text-accent font-semibold">{review.tool_name}</p>
              </div>
            </div>

            {review.best_for && (
              <div className="mb-4">
                <p className="text-sm text-dt-muted mb-1">Best For:</p>
                <p className="text-base text-dt">{review.best_for}</p>
              </div>
            )}

            {review.pricing_summary && (
              <div>
                <p className="text-sm text-dt-muted mb-1">Pricing:</p>
                <p className="text-base text-dt">{review.pricing_summary}</p>
              </div>
            )}
          </div>

          <div className="flex items-center gap-4 text-sm text-dt-muted mb-4">
            <span>By {review.author}</span>
            <span>{new Date(review.published_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
            <span>{getReadingTime(review.word_count)}</span>
            <span>{(review.word_count || 0).toLocaleString()} words</span>
          </div>
        </header>

        <AffiliateDisclosure />

        {/* Build-time generated review HTML - trusted content from our pipeline */}
        <div className="prose prose-lg max-w-none mt-8">
          <div dangerouslySetInnerHTML={{ __html: firstHalf }} />
        </div>

        {hasEnoughContent && (
          <div className="my-10"><NewsletterSignup variant="inline" /></div>
        )}

        {hasEnoughContent && secondHalf && (
          <div className="prose prose-lg max-w-none">
            <div dangerouslySetInnerHTML={{ __html: secondHalf }} />
          </div>
        )}

        <div className="my-10 p-6 bg-dark-surface rounded-lg border border-dark-border">
          <h2 className="text-xl font-bold text-dt mb-3">The Verdict</h2>
          <p className="text-base text-dt mb-3">{review.verdict}</p>
          {review.tool_website && (
            <a href={review.tool_website} target="_blank" rel="noopener nofollow sponsored" className="inline-block px-4 py-2 bg-accent text-black font-semibold rounded transition-colors hover:bg-accent/80">
              Visit {review.tool_name} →
            </a>
          )}
        </div>

        {review.alternatives && review.alternatives.length > 0 && (
          <aside className="mt-12 pt-8 border-t border-dark-border">
            <h2 className="text-xl font-bold text-dt mb-3">Alternatives</h2>
            <p className="text-sm text-dt-muted mb-6">Other tools worth considering:</p>
            <ul className="space-y-2">
              {review.alternatives.map((alt, i) => (
                <li key={i} className="text-dt">• {alt}</li>
              ))}
            </ul>
          </aside>
        )}

        <div className="mt-12 mb-8"><NewsletterSignup variant="banner" /></div>

        {relatedReviews && relatedReviews.length > 0 && (
          <aside className="mt-12 pt-8 border-t border-dark-border" aria-label="Related Reviews">
            <h2 className="text-xl font-bold text-dt mb-4">More Reviews</h2>
            <p className="text-sm text-dt-muted mb-6">Discover our other in-depth tool reviews.</p>
            <div className="grid md:grid-cols-3 gap-4">
              {relatedReviews.map(rel => (
                <Link
                  key={rel.slug}
                  href={`/reviews/${rel.slug}/`}
                  className="card hover:border-accent/30 flex flex-col"
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className="badge-blue text-xs">{rel.category}</span>
                    <span className="text-xs text-accent font-semibold">
                      {rel.rating}
                    </span>
                  </div>
                  <h3 className="font-semibold text-dt text-sm leading-snug mb-2">{rel.tool_name}</h3>
                  <p className="text-xs text-dt-muted line-clamp-2 mt-auto">{rel.excerpt}</p>
                </Link>
              ))}
            </div>
          </aside>
        )}

        <footer className="mt-8 pt-8 border-t border-dark-border">
          <Link href="/reviews/" className="text-accent hover:text-cyan-300 font-medium transition-colors">&larr; Back to all reviews</Link>
        </footer>
      </article>
    </Layout>
  )
}

export async function getStaticPaths() {
  return { paths: getAllReviews().map(r => ({ params: { slug: r.slug } })), fallback: false }
}

export async function getStaticProps({ params }) {
  const review = getReviewBySlug(params.slug)
  if (!review) return { notFound: true }

  const allReviews = getAllReviews().filter(r => r.slug !== review.slug)
  const relatedReviews = allReviews.slice(0, 3).map(r => ({
    slug: r.slug,
    tool_name: r.tool_name,
    excerpt: r.excerpt,
    category: r.category,
    rating: r.rating,
  }))

  return { props: { review, relatedReviews } }
}
