import Layout from '../../components/Layout'
import { AffiliateDisclosure } from '../../components/AffiliateLink'
import NewsletterSignup from '../../components/NewsletterSignup'
import Breadcrumbs from '../../components/Breadcrumbs'
import Link from 'next/link'
import { getAllArticles, getArticleBySlug, getReadingTime } from '../../lib/articles'

const SITE_URL = 'https://pilottools.ai'

export default function ArticlePage({ article }) {
  if (!article) return null

  const canonicalUrl = `${SITE_URL}/blog/${article.slug}/`
  const structuredData = [
    {
      "@context": "https://schema.org", "@type": "Article",
      "headline": article.title,
      "description": article.meta_description || article.excerpt,
      "author": { "@type": "Organization", "name": "PilotTools" },
      "publisher": { "@type": "Organization", "name": "PilotTools", "url": SITE_URL },
      "datePublished": article.published_date,
      "mainEntityOfPage": canonicalUrl,
      "wordCount": article.word_count,
      "keywords": (article.keywords || []).join(', ')
    }
  ]

  // Article HTML is generated by our build-time content pipeline (not user input)
  const contentHtml = article.html || ''
  const midPoint = Math.floor(contentHtml.length / 2)
  const splitIndex = contentHtml.indexOf('</p>', midPoint)
  const hasEnoughContent = contentHtml.length > 1000 && splitIndex !== -1
  const firstHalf = hasEnoughContent ? contentHtml.substring(0, splitIndex + 4) : contentHtml
  const secondHalf = hasEnoughContent ? contentHtml.substring(splitIndex + 4) : ''

  return (
    <Layout
      title={article.meta_title || article.title}
      description={article.meta_description || article.excerpt}
      canonical={canonicalUrl}
      ogType="article"
      structuredData={structuredData}
    >
      <Breadcrumbs items={[
        { label: 'Home', href: '/' },
        { label: 'Blog', href: '/blog/' },
        { label: article.title }
      ]} />

      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <header className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="badge-blue">{article.category}</span>
            {article.tags && article.tags.slice(0, 3).map(tag => (
              <span key={tag} className="badge-green text-xs">{tag}</span>
            ))}
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-dt mb-4 leading-tight">{article.title}</h1>
          <div className="flex items-center gap-4 text-sm text-dt-muted">
            <span>By {article.author}</span>
            <span>{new Date(article.published_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
            <span>{getReadingTime(article.word_count)}</span>
            <span>{article.word_count.toLocaleString()} words</span>
          </div>
        </header>

        <AffiliateDisclosure />

        {/* Build-time generated article HTML - trusted content from our pipeline */}
        <div className="prose prose-lg max-w-none mt-8">
          <div dangerouslySetInnerHTML={{ __html: firstHalf }} />
        </div>

        {hasEnoughContent && (
          <div className="my-10"><NewsletterSignup variant="inline" /></div>
        )}

        {hasEnoughContent && secondHalf && (
          <div className="prose prose-lg max-w-none">
            <div dangerouslySetInnerHTML={{ __html: secondHalf }} />
          </div>
        )}

        <div className="mt-12 mb-8"><NewsletterSignup variant="banner" /></div>

        <footer className="mt-8 pt-8 border-t border-dark-border">
          <Link href="/blog/" className="text-accent hover:text-cyan-300 font-medium transition-colors">&larr; Back to all articles</Link>
        </footer>
      </article>
    </Layout>
  )
}

export async function getStaticPaths() {
  return { paths: getAllArticles().map(a => ({ params: { slug: a.slug } })), fallback: false }
}

export async function getStaticProps({ params }) {
  const article = getArticleBySlug(params.slug)
  if (!article) return { notFound: true }
  return { props: { article } }
}
