"""ToolPilot weekly newsletter sender via ConvertKit broadcast API."""

import json
import sys
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Add project root to path for imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from email_marketing.convertkit_setup.convertkit_automation import ConvertKitManager


def send_newsletter(newsletter_path: str) -> dict:
    """Read newsletter JSON and create a ConvertKit broadcast.

    Args:
        newsletter_path: Path to the newsletter JSON file
            (generated by ai-tools-hub/scripts/generate-newsletter.js)

    Returns:
        ConvertKit broadcast response
    """
    # Read newsletter data
    with open(newsletter_path, 'r') as f:
        newsletter = json.load(f)

    subject = newsletter.get('subject', 'ToolPilot AI Weekly')
    html_content = newsletter.get('html_content', '')
    preview_text = newsletter.get('preview_text', '')

    if not html_content:
        raise ValueError('Newsletter has no html_content')

    logger.info(f'Sending newsletter: "{subject}"')

    # Wrap content in a styled email template
    full_html = f"""
<div style="max-width: 600px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1f2937;">
  <div style="background: linear-gradient(135deg, #4f46e5, #3b82f6); padding: 24px; text-align: center; border-radius: 12px 12px 0 0;">
    <h1 style="color: white; font-size: 24px; margin: 0;">ToolPilot AI Weekly</h1>
    <p style="color: #c7d2fe; font-size: 14px; margin: 4px 0 0;">Make Money & Save Money with AI</p>
  </div>
  <div style="padding: 24px; background: #ffffff; border: 1px solid #e5e7eb; border-top: none;">
    {html_content}
  </div>
  <div style="padding: 16px; text-align: center; background: #f9fafb; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
    <p style="font-size: 12px; color: #9ca3af; margin: 0;">
      You received this email because you subscribed to ToolPilot AI Weekly.<br>
      <a href="{{{{ unsubscribe_url }}}}" style="color: #6366f1;">Unsubscribe</a> |
      <a href="https://toolpilot-hub.netlify.app" style="color: #6366f1;">Visit ToolPilot</a>
    </p>
  </div>
</div>
"""

    # Create broadcast via ConvertKit
    manager = ConvertKitManager()
    result = manager.create_broadcast(
        subject=subject,
        content=full_html,
        description=f"ToolPilot Weekly - {newsletter.get('week_of', 'auto')}",
        preview_text=preview_text,
        public=True,
    )

    logger.info(f'Broadcast created successfully: {result}')
    return result


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python email_marketing/toolpilot_newsletter.py <newsletter.json>')
        sys.exit(1)

    newsletter_file = sys.argv[1]
    result = send_newsletter(newsletter_file)
    print(f'Newsletter broadcast created: {json.dumps(result, indent=2)}')
