"""
Verify Amazon ASINs against the Rainforest API.

Checks if each ASIN is valid and the product is available.
Generates a verification report with status for each link.
"""

import json
import argparse
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional

# Import our Rainforest client
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from automation.amazon.rainforest_client import RainforestClient

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def verify_asins(asins_data: dict, client: Optional[RainforestClient] = None) -> dict:
    """
    Verify all ASINs in the extracted data.

    Args:
        asins_data: Output from extract_asins.py
        client: Optional pre-configured RainforestClient

    Returns:
        Verification report dict
    """
    if client is None:
        client = RainforestClient()

    results = []
    valid_count = 0
    invalid_count = 0
    error_count = 0

    for item in asins_data.get('asins', []):
        asin = item['asin']
        logger.info(f"Verifying {asin}...")

        try:
            verification = client.verify_asin(asin)

            if verification['valid']:
                status = 'valid'
                valid_count += 1
            else:
                status = 'invalid'
                invalid_count += 1

            results.append({
                'asin': asin,
                'status': status,
                'title': verification.get('title'),
                'price': verification.get('price'),
                'availability': verification.get('availability'),
                'error': verification.get('error'),
                'locations': item.get('locations', []),
                'verified_at': datetime.utcnow().isoformat(),
            })

        except Exception as e:
            error_count += 1
            results.append({
                'asin': asin,
                'status': 'error',
                'title': None,
                'price': None,
                'availability': None,
                'error': str(e),
                'locations': item.get('locations', []),
                'verified_at': datetime.utcnow().isoformat(),
            })
            logger.error(f"Error verifying {asin}: {e}")

    return {
        'verified_at': datetime.utcnow().isoformat(),
        'summary': {
            'total': len(results),
            'valid': valid_count,
            'invalid': invalid_count,
            'errors': error_count,
        },
        'results': results,
    }


def generate_github_issue_body(report: dict) -> str:
    """
    Generate GitHub issue body for broken links.

    Args:
        report: Verification report

    Returns:
        Markdown formatted issue body
    """
    invalid = [r for r in report['results'] if r['status'] != 'valid']

    if not invalid:
        return ""

    body = f"""## Broken Affiliate Links Detected

**Verification Time:** {report['verified_at']}
**Summary:** {report['summary']['invalid']} invalid, {report['summary']['errors']} errors out of {report['summary']['total']} total ASINs

### Invalid Links

"""

    for item in invalid:
        asin = item['asin']
        error = item.get('error', 'Unknown error')

        body += f"#### ASIN: `{asin}`\n"
        body += f"- **Status:** {item['status']}\n"
        body += f"- **Error:** {error}\n"
        body += f"- **Locations:**\n"

        for loc in item.get('locations', [])[:3]:  # Limit to 3 locations
            body += f"  - `{loc['file']}` line {loc['line']}\n"

        body += "\n"

    body += """### Suggested Actions

1. Remove or replace the invalid ASINs with working alternatives
2. Search for replacement products in the same category
3. Update both the ASIN and product image URL

### How to Find Replacement ASINs

1. Go to [Amazon.com](https://amazon.com)
2. Search for a similar product
3. Copy the ASIN from the URL (e.g., `/dp/B07HBTY3Z2`)
4. Update the link with the new ASIN

---
*This issue was auto-generated by the link verification workflow.*
"""

    return body


def main():
    parser = argparse.ArgumentParser(
        description='Verify Amazon ASINs via Rainforest API'
    )
    parser.add_argument(
        '--input',
        default='asins.json',
        help='Input JSON file from extract_asins.py'
    )
    parser.add_argument(
        '--output',
        default='verification_report.json',
        help='Output verification report JSON'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Skip API calls, just test the flow'
    )

    args = parser.parse_args()

    # Load extracted ASINs
    input_path = Path(args.input)
    if not input_path.exists():
        logger.error(f"Input file not found: {args.input}")
        logger.info("Run extract_asins.py first to generate the input file")
        return 1

    asins_data = json.loads(input_path.read_text())
    logger.info(f"Loaded {asins_data['unique_asins']} ASINs to verify")

    if args.dry_run:
        logger.info("DRY RUN - skipping API verification")
        report = {
            'verified_at': datetime.utcnow().isoformat(),
            'summary': {'total': asins_data['unique_asins'], 'valid': 0, 'invalid': 0, 'errors': 0},
            'results': [],
            'dry_run': True,
        }
    else:
        # Run verification
        report = verify_asins(asins_data)

    # Write report
    output_path = Path(args.output)
    output_path.write_text(json.dumps(report, indent=2))
    logger.info(f"Report written to {args.output}")

    # Print summary
    summary = report['summary']
    print(f"\n{'='*50}")
    print("VERIFICATION SUMMARY")
    print(f"{'='*50}")
    print(f"Total ASINs:  {summary['total']}")
    print(f"Valid:        {summary['valid']} ✓")
    print(f"Invalid:      {summary['invalid']} ✗")
    print(f"Errors:       {summary['errors']} ⚠")
    print(f"{'='*50}")

    # Check if we need to create an alert
    if summary['invalid'] > 0 or summary['errors'] > 0:
        print("\n⚠️  ACTION REQUIRED: Some affiliate links need attention!")
        issue_body = generate_github_issue_body(report)

        # Save issue body for GitHub Action
        issue_path = Path('github_issue_body.md')
        issue_path.write_text(issue_body)
        print(f"GitHub issue body saved to {issue_path}")

        return 1  # Exit with error to trigger alert

    print("\n✅ All affiliate links verified successfully!")
    return 0


if __name__ == "__main__":
    exit(main())
